### ISSUE TITLE
Eliminate Text.HTML.Download

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/tagsoup#14]
From https://code.google.com/p/ndmitchell/issues/detail?id=368

One user reported that the network dependency in tagsoup was causing issues. Since this is only used by a deprecated part of the package it seems worth trying to remove.

A search of Hackage reveals only two users of this module, hackage-plot and hackage-sparks, both by Dons. Plan is to create patches, get them submitted, wait for these packages to be uploaded, and then delete it.

Dons didn't reply, so I have made them off by default, and can be installed with a flag.

**Comment by seagreen** [comment]
It's been almost a year, so you're probably good now. I'd be happy to remove `Text.HTML.Download` if you'd like a small PR.

**Comment by ndmitchell** [comment]
Agreed, the time has come. PR would be most welcome.

**Comment by seagreen** [comment]
Sure thing: https://github.com/ndmitchell/tagsoup/pull/56

**Comment by ndmitchell** [comment]
All done and released as tagsoup-0.14. Thanks for the patch.

**Comment by seagreen** [comment]
Heck all I did was delete stuff. That's fun not work:)

**Comment by ndmitchell** [comment]
If only I could persuade people at work to delete old code!!!
