### ISSUE TITLE
~== should be case insensitive

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/tagsoup#19]
From https://code.google.com/p/ndmitchell/issues/detail?id=385

José Romildo Malaquias writes:

Currently the comparison of the name of open and close tags in the
inexact match operator (~==) of the Text.HTML.TagSoup package is case
sensitive. Maybe it is better to let this comparison be case
insensitive, as it should be irrelavant to the meaning of the HTML
code. The same would apply to the name of attributes in open tags.

I have just noticed that the package tagsoup-parsec already has parsers
for open and close tags which are already case insensitive.

I replied: Perhaps that does make sense. Not sure, but definitely worth thinking about.

Come to think of it, does anyone searching for `<span>` not also want to find `<SPAN>`? I doubt it. Perhaps the tag names and attribute names should be case insensitive, but the text values should still be case sensitive.

**Comment by ndmitchell** [comment]
However, with HTML5, do I already lowercase all tags when parsing anyway? If so, this is fixed already.

**Comment by ndmitchell** [comment]
Just checked, I leave tags as they are case wise, so the bug is still relevant.

**Comment by rcook** [comment]
Does this relate to issue #2?

**Comment by ndmitchell** [comment]
Better to canonicalise when parsing, see #48, which would fix this. Thanks for the note @rcook.
