### ISSUE TITLE
Consider renaming 'tagsoup' test tool to avoid collision with 

### ISSUE THREAD

**Issue by trofi** [ndmitchell/tagsoup#26]
Original report: https://bugs.gentoo.org/show_bug.cgi?id=547734

/usr/bin/tagsoup is being provided by multiple packages in gentoo:
  dev-haskell/tagsoup
     Homepage:            http://community.haskell.org/~ndm/tagsoup/
     Description:         Parsing and extracting information from (possibly malformed) HTML/XML documents

  dev-java/tagsoup
     Homepage:            http://mercury.ccil.org/~cowan/XML/tagsoup/
     Description:         A SAX-compliant parser written in Java

We've renamed tagsoup to haskell-tagsoup in gentoo to avoid collision.

What do you think ofslightly  changing a tool name
to something like 'hstagsoup' / 'hsts' / other?

**Comment by ndmitchell** [comment]
It's the test tool, so I'm not too fussed what it is called. Is `test-tagsoup` still too generic?

**Comment by trofi** [comment]
test-tagsoup sounds fine. We don't have such binary in gentoo.

**Comment by ndmitchell** [comment]
Done, and released as tagsoup-0.13.5. Let me know if you need anything else.
