### ISSUE TITLE
Should a stack file be added?

### ISSUE THREAD

**Issue by TheKing42** [ndmitchell/tagsoup#29]

**Comment by ndmitchell** [comment]
My general principle is if stack init works to generate a perfectly valid stack file that works, then don't bother. I believe that's true here, but if you think the default stack file is lacking something, let me know.

**Comment by ndmitchell** [comment]
I now have a test that everything works with stack init (https://ci.appveyor.com/project/ndmitchell/tagsoup), and I've updated my development guidelines to say that I don't normally include stack.yml which can be auto generated (https://github.com/ndmitchell/neil#quirks) so marking this closed.

**Comment by TheKing42** [comment]
Oh, so if you want to use stack, you can just run `stack init` and go? (I didn't know that about stack.)

**Comment by TheKing42** [comment]
Oh, and for historical purposes, the update to the development guidelines occured in a42b7652ed1ec2b1dd21eb70082561d1e5f5ab87.

**Comment by TheKing42** [comment]
Oh, and for historical purposes, this was closed by a42b7652ed1ec2b1dd21eb70082561d1e5f5ab87.
