### ISSUE TITLE
Can StringLike have a IsString dependency?

### ISSUE THREAD

**Issue by TheKing42** [ndmitchell/tagsoup#34]
One nice thing would be if `StringLike` was a subclass of [`IsString`](https://hackage.haskell.org/package/base-4.8.2.0/docs/Data-String.html#t:IsString) from the base package. This way, you don't have to require parameters to satisfy both `StringLike` and `IsString`, or convert between them (which can be annoying if you want to keep things polymorphic). It also allows overloadedstrings to work with `StringLike`.

It would be trivial to do this, and you could even give `fromString` a default implementation.

If we want to do this, I could implement this.

**Comment by ndmitchell** [comment]
Sounds sensible. How recent is IsString? I guess as long as it's GHC 7.4 and beyond or guarded by CPP that should be fine (no need to CPP if it's in 7.4).

**Comment by TheKing42** [comment]
It's in base 4.8.0.0, so it's probably fine. (I guess the automated tests will catch stuff.)
