### ISSUE TITLE
Hit count sample no longer works

### ISSUE THREAD

**Issue by rcook** [ndmitchell/tagsoup#36]
Unfortunately, the URL in the hit count example in `README.md`, i.e. `http://www.haskell.org/haskellwiki/Haskell`, returns a 302 "moved temporarily" HTTP response. I'll see if I can figure out a way to rewrite the sample to work.

Update: I tried changing the URL to `https://wiki.haskell.org/Haskell`. Unfortunately, the new front page no longer includes a hit count.

**Comment by TheKing42** [comment]
:cry: I suppose we could place an issue here: https://github.com/haskell-infra/hl

**Comment by rcook** [comment]
I was thinking that a nice replacement example would be the Hackage page for this package: http://hackage.haskell.org/package/tagsoup. The example could extract the "Downloads" count from this page. I would rewrite the sample myself, but I haven't figured out how to use the package yet!

**Comment by pellagic-puffbomb** [comment]
You could just switch it to the last modified date at https://wiki.haskell.org/Haskell, which contains the same markup:
```
<ul id="f-list">
					<li id="lastmod"> This page was last modified on 9 September 2013, at 22:38.</li>
					<li id="copyright">Recent content is available under <a href="/HaskellWiki:Copyrights" title="HaskellWiki:Copyrights">a simple permissive license</a>.</li>
```

Which would be simply:
```
haskellHitCount = do
    src <- openURL "http://haskell.org/haskellwiki/Haskell"
    let modified = fromFooter $ parseTags src
    putStrLn $ modified
    where fromFooter = innerText . take 2 . dropWhile (~/= "<li id=lastmod>")
```

Alternately, to get the "Downloads" count on the hackage page, something like the following should work, I think:

```
let table = dropWhile (~/= "<table class=properties>") $ parseTags src
let downloads = fromTagText . head . drop 1 . dropWhile (~/= "Downloads") $ filter isTagText table
```

**Comment by TheKing42** [comment]
+1 for Downloads count

**Comment by rcook** [comment]
I'll update the example to use last modified date for now. If I have time, I'll add an example that does download count too.

**Comment by TheKing42** [comment]
@rcook It appears that https://github.com/ndmitchell/tagsoup/blob/master/TagSoup/Sample.hs is where this would go.

**Comment by rcook** [comment]
@TheKing42 : Thanks!

**Comment by TheKing42** [comment]
@rcook (You probably know this, but I didn't, so I tell you just to be sure. To run it in `ghci`, you need to do `cabal repl` at the top level of the repo, and then you can do `import` or `:l`. This will make sure things are being built against the things they should. (Took me a bit to figure that out.))

**Comment by ndmitchell** [comment]
Thanks @rcook and @TheKing42 for your patches and figuring out the problem and solution. I raised #40 to use Travis to run the demos, and hopefully catch such issues before users run into them.
