### ISSUE TITLE
TagSoup uses unbounded stack space while parsing a single tag

### ISSUE THREAD

**Issue by rspeer** [ndmitchell/tagsoup#50]
I expected to be able to use TagSoup to parse arbitrary HTML, but what I've found is that a single tag with lots of content (and by "lots" I only mean hundreds of kilobytes) can fill up the Haskell stack and crash my program. I've switched to `fast-tagsoup` which doesn't have this problem, but this seems like a relevant bug in tagsoup.

If `aaaa.html` is a file of the form:

```html
<html><body>[286 KB of content goes here]</body></html>
```

then the following Haskell program will crash when compiled with GHC's defaults, using TagSoup 0.13.8:

```haskell
module Main where
import System.IO
import Text.HTML.TagSoup

main :: IO ()
main = do
  text <- openFile "aaaa.html" ReadMode >>= hGetContents
  let tags = parseTags text in putStrLn (show (tags !! 4))
```

The error it crashes with is:

```
Stack space overflow: current size 8388608 bytes.
Use `+RTS -Ksize -RTS' to increase it.
```

I can of course increase the stack size, but all that means is that it takes a longer tag to crash it.

If you want a complete example including the HTML file, I put it up at https://gist.github.com/rspeer/57c8d5995bc281e284b4 . I replaced every non-linebreak character in the HTML with "a" to emphasize that the content doesn't matter.

**Comment by ndmitchell** [comment]
Thanks! Using the techniques at http://neilmitchell.blogspot.co.uk/2015/09/detecting-space-leaks.html it took about 2 minutes to track down and fix. It used to run in 8Mb of stack, and now it runs in less than 1Kb.
