### ISSUE TITLE
Issue about working with `OverloadedStrings` extension

### ISSUE THREAD

**Issue by lxyu** [ndmitchell/tagsoup#55]
I come across a same error once asked here http://stackoverflow.com/questions/7352213/haskell-tagsoup-library-with-overloadedstrings

The error looks like:

```haskell
No instance for (TagRep t0) arising from a use of ‘~==’
    The type variable ‘t0’ is ambiguous
    Note: there are several potential instances:
      instance Text.StringLike.StringLike str => TagRep (Tag str)
        -- Defined in ‘Text.HTML.TagSoup’
      instance TagRep String -- Defined in ‘Text.HTML.TagSoup’
    In the first argument of ‘sections’, namely ‘(~== "<input>")’
    In the first argument of ‘(.)’, namely ‘sections (~== "<input>")’
    In the second argument of ‘(<$>)’, namely
      ‘sections (~== "<input>")
       . takeWhile (~/= s "<input name=user>")
```

Currently I'm using the workaround posted in the answer, add a helper function:

```haskell
s :: String -> String
s = id

-- have to add `s` before string everywhere.. for example 
let sth = sections (~== s "<input>") . takeWhile (~/= s "<input name=user>") $ tags
```

It still looks wordy. Is there a better solution to this problem?

**Comment by ndmitchell** [comment]
The answer at http://stackoverflow.com/a/7353018/160673 is pretty good, but there's a final alternative which I added as an answer at http://stackoverflow.com/a/37574220/160673. Hopefully that gives you something less wordy.
