### ISSUE TITLE
Incorrect source position before comment.

### ISSUE THREAD

**Issue by jgm** [ndmitchell/tagsoup#70]
With tagsoup 0.14.2:
``` haskell
Prelude Text.HTML.TagSoup> parseTagsOptions parseOptions{ optTagWarning = True, optTagPosition = True } "<div><!--foo-->bar</div>"
[TagPosition 1 1,TagOpen "div" [],TagPosition 1 8,TagComment "foo",TagPosition 1 16,TagText "bar",TagPosition 1 19,TagClose "div"]
```

If I'm not terribly confused, the third token should be `TagPosition 1 6`, not `TagPosition 1 8`.  The open tag consists of five characters.  Is this a bug?

See jgm/pandoc#4282.

**Comment by jgm** [comment]
Compare
```
Prelude Text.HTML.TagSoup> parseTagsOptions parseOptions{ optTagWarning = True, optTagPosition = True } "<div>a</div>"
[TagPosition 1 1,TagOpen "div" [],TagPosition 1 6,TagText "a",TagPosition 1 7,TagClose "div"]
```
Here we get `TagPosition 1 6`, which I'd expect in both cases after the open tag.

**Comment by ndmitchell** [comment]
Thanks for the report - yep - I had a `pos` in the wrong place. Moved and tests added. I'll make a release as soon as it passes my CI.

**Comment by jgm** [comment]
Excellent, thanks!

**Comment by ndmitchell** [comment]
0.14.3 now out - let me know if you find any further issues.

**Comment by jgm** [comment]
Everything looks good now, thanks for the quick response!

+++ Neil Mitchell [Jan 21 18 17:33 ]:
>   0.14.3 now out - let me know if you find any further issues.
