### ISSUE TITLE
Escape single quote (') characters as &#39;

### ISSUE THREAD

**Issue by RyanGlScott** [ndmitchell/tagsoup#74]
I was surprised to discover that the `escapeXml` function escapes double quotes (`"`) but not single quotes (`'`). Digging into the source code of `tagsoup`, I found this comment:

https://github.com/ndmitchell/tagsoup/blob/99a43e9c62627a2541e55b2774bf0f1c9c31f11d/src/Text/HTML/TagSoup/Entity.hs#L73-L82

This suggests that the reason that single quotes aren't escaped is due to Internet Explorer not supporting `&apos;`. But this feels a bit too conservative, since Internet Explorer _does_ support `&#39;`, as suggested [here](http://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents/1091953#1091953). (Credit goes to [this `stache` pull request](https://github.com/JustusAdam/mustache/pull/28) for that idea.)

Would you be open to `escapeXml` escaping single quotes as `&#39;` instead?

**Comment by ndmitchell** [comment]
Having Google'd, there doesn't seem to be a consistent set... Quite a lot do `&<>`, some more do `&<>"`, others do `&<>"'` and some add `/` in there for reasons I can't fathom. I think you're right, I'd happily take a patch to make it escape `'` to the numeric variant.

If this is the only function you're using in tagsoup, you may wish to consider using https://hackage.haskell.org/package/extra-1.6.9/docs/Data-List-Extra.html#v:escapeHTML instead (which also doesn't escape ', but for which I'd also happily take a patch).

**Comment by RyanGlScott** [comment]
I've opened #75 and ndmitchell/extra#38 to incorporate this fix into `tagsoup` and `extra`, respectively.
