### ISSUE TITLE
`tagsoup` binary no longer avaliable.

### ISSUE THREAD

**Issue by wizzup** [ndmitchell/tagsoup#77]
The Readme mention `tagsoup` [binary](https://github.com/ndmitchell/tagsoup#using-the-tagsoup-program) but seem it no longer provided.

related: https://github.com/NixOS/nixpkgs/issues/55268

**Comment by ndmitchell** [comment]
Thanks for letting me know. I removed it when Cabal got support for test suites, and things like curl/wget became sufficiently ubiquitous that providing a way to download a file no longer provided much value. I've updated the readme.
