### ISSUE TITLE
StringLike CaseInsensitive

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [ndmitchell/tagsoup#82]
Would you be interested in adding a CI instance for StringLike?

```haskell
instance (StringLike a, FoldCase a) => StringLike (CI a) where
  empty = CI.mk SL.empty
  cons c (CI.original -> cs) = CI.mk $ SL.cons c cs
  uncons = (fmap $ fmap CI.mk) . SL.uncons . CI.original
  toString = SL.toString . CI.original
  fromChar = CI.mk . SL.fromChar
  strConcat = CI.mk . SL.strConcat . fmap CI.original
  strNull = SL.strNull . CI.original
  append x y = CI.mk $ SL.append (CI.original x) (CI.original y)
  strMap f x = CI.mk $ SL.strMap f $ CI.original x
```

**Comment by ndmitchell** [comment]
I assume that would require an additional package dependency? If so, then no - unfortunately the orphan instance problem makes this really hard to solve :(

**Comment by BebeSparkelSparkel** [comment]
I can see not wanting to add an dependency. I was however running into the problem where some idiot was using different cases for the openers and closers. CI allows me to handle the difference.

**Comment by ndmitchell** [comment]
I can see why it's useful, but the dependency would be annoying. Haskell doesn't have a great answer, so I suggest a local orphan instance, or if you are putting this in a library, and a custom newtype over CI and give an instance for that.
